INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2007-06-04','P','Abel De Jesus Cerrato',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-01','P','Alberto David Bonilla',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-06-01','C','Amy Lagos',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-05-01','C','Amy Lizeth Hernandez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1998-08-03','P','Ana Gloria Ramos',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-03-03','C','Ana Ofelia Motiño',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-09-01','C','Axel Javier Zelaya',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-02','P','Brenda Concepcion Cruz',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-06-13','P','Carlos Ariel Tróchez Zelaya',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-07-01','C','Celeo Joel Diaz',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-02','P','Cesar Alberto Martinez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-04-01','C','Cindy Lyonela Garcia M.',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-01-03','C','Cinthia Carolina Padilla',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1996-07-01','P','Claudia Marina Sarmiento',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1996-07-01','P','Clinton Olivera',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2006-01-02','P','Daisy Yorleni Rodriguez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1992-09-01','P','Daniel Antonio Ochoa',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-02','C','Daniel Rivera',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2008-03-04','C','David Gerardo Bracamonte',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-03-01','C','Digna Melissa Galvez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-01-01','C','Edgardo Omar Segura',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-01-01','C','Edwin Arturo Fernandez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-03-06','C','Ela Maria Zelaya',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1986-01-02','P','Ely Catalina Dominguez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-06-13','P','Eneida Jimenez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-03-01','C','Erick Fernando Aguiriano',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-07-25','C','Eva Leonor Calix',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-08-06','P','Frida Nadesda Mejia',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2013-01-01','C','Gloria Maria Inestroza',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2000-10-20','P','Hector Escoto',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-03-01','P','Hector Saul Lopez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2008-03-01','P','Hector Tulio Garcia',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-10-01','C','Hilda Xiomara Castellano',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-03-01','C','Ilsi Donaire',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-01-02','P','Iris Raquel Benitez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-03-01','C','Ivonne Waleska Canales',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-11-03','P','Javier Enrique Zelaya',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-02','P','Joel Turcios',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2006-01-02','P','Jose Antonio Zelaya',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-08-01','P','Jose Braz Guimaraez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1998-08-03','P','Jose Enrique Mendez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2007-06-04','P','Jose Leon Rivera',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-01','P','Jose Luis Pinto',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1999-07-01','P','Juana Lizeth Cruz',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-09-01','C','Julissa Yaneth Andrade',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2006-01-02','P','Lesbia Yabeth Sandoval',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2007-06-04','P','Ligia Geraldina Umaña',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-07-01','C','Lucy Maribel Martinez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-10-24','C','Luis Carlos Trochez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-01','P','Luis Carlos Trochez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-01-02','C','Luis Fernando Aguilar',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2008-03-01','P','Luis Guillermo Moraga',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2007-02-12','P','Luis Ramon Valderramos',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-02','P','Lyn Dayana Olivera',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2006-07-01','C','Marcos Rolando Medina',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-01','P','Mario Jose Gonzales',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-03-01','P','Melba Patricia Cruz',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-04-01','C','Melissa Lilibeth Turcios',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1998-08-03','P','Mericia Yolibeth Breve',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-04-10','C','Napoleon Valerio Zapata',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1993-04-01','C','Nicolas Alberto Irias',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-01-01','C','Oly Lideny Oliva',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-04-01','C','Orquidea Zelaya',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-02','P','Osman Noel Garcia Avila',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-03-01','C','Rafael Eduardo Santos',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-01','P','Ramon Edgardo Irias',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2004-01-01','P','Ramon Henriquez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-06-01','C','Sadia Melissa Banegas',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-06-13','P','Samuel Gustavo Rodriguez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-01','P','Sandra Carlota Matute',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-02','P','Santos Jubinaldo Flores',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-01','P','Sara Carolina Paz',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-10-01','C','Sergio Alejandro Cerna',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-11-03','P','Silvia Yaneth Hernandez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-01-01','C','Teresa Maria Reyes',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-07-01','C','Vanessa Jose Diaz',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-11-03','P','Victor Manuel Zepeda',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-02-16','C','Vilma Galvez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-01-02','C','Wilian Alexander Duron',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-03-01','P','Wilson Sabonge',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1996-07-01','P','Ziomara Yamileth Ceballos',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1993-04-01','P','Zoila Adilia Rivera',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2008-03-03','P','Adonia Anaizel Diaz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-07-01','C','Alba Elizabeth Flores',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-01','C','Alba Leticia Tejeda Cano',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-01-02','P','Alba Lopez Montalvan',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1980-05-01','P','Alba Margarita Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-11-01','P','Alba Maria Reyes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-11','C','Alba Maricela Figueroa',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-11-01','P','Alba Marina Pavon',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1989-02-01','P','Alba Marina Vásquez D',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-09-01','C','Alba Yadira Rodriguez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-02-20','C','Alex Matute',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-10-01','C','Altagracia del carmen reyes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1978-02-01','P','Amalia Carmén Osorio Garrido',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-07-01','C','Amanda Lucila Calix',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-07-01','C','Ana Cerna',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1999-02-01','P','Ana lizeth Ayala',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-08-01','C','Ana Maria Cartejena',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-07-01','C','Ana Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1999-04-12','P','Ana Rosa Romero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1985-02-01','P','Ana Rosario Hdz Montes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-07-01','C','Ana Victoria Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-11-03','P','Anabel del Carmen Cardona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-09-01','P','Angela Maritza Funez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1991-06-03','P','Angela Padilla Meza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-05-01','C','Angelica Yamileth Bardales',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-11-19','C','Ansy Marilu Puerto',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2004-07-02','P','Aracely Maribel Gomez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1985-02-15','P','Berlinda Lily Rodriguez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1993-09-01','P','Bertha Estela Turcios',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-05-01','C','Bessy Mejia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-05-01','C','Bessy Yasmin Flores',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-02-01','C','Betina Petronila Turcios',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-02-01','C','Betina Petronila turcios',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1990-05-02','P','Bety Leticia Varela',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1987-07-01','P','Blanca Lidia Sierra',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-10-01','P','Breiner Paul Muñoz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-01-02','P','Brenda Flores',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-09-23','P','Carlos Everto Duarte',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-01-04','P','Carlos ruben varela',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1991-04-04','P','Carmen Rosmeri Alonzo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-08-01','C','Cindi Bonilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-09-01','C','Cindi Graciel elvir',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-09-03','P','Claudia Barahona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-01','P','Claudia Sarmiento',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-01-03','P','Coritza Landelina Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2008-04-01','C','Damari Valladares',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-04','C','Damaris Mireya Galvez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-08-22','P','Dariela Elena Medina',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2001-08-01','P','Dayanara Varinia Licona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1990-07-02','P','Daysi Sagrario Hernandez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-06-20','C','Deisy Pineda',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-03-01','P','Denis Alaberto Andino',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-07-01','P','Deysi Alejandrina Mendoza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-02-02','C','Deysi Maria Moradel',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-02-02','C','Deysi Moradel Carias',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2013-04-05','C','Diana solorzano',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-01-01','C','Diana Yamileth Lopez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1990-05-02','P','Digna Maribel Garcia Suarez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1999-04-19','P','Dilian Margoth Acosta',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-02-01','C','Dina Veronica Carias',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2007-02-26','P','Dina Yolani Acosta',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-01-01','P','Doris Antonia Licona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2006-09-20','P','Dulce Paz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-02-15','P','Dulmi Yolani Romero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-03-26','C','Eda Beatris Hernandez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-05-05','C','Edis Etelvina Rodas',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-01-02','P','Edith Jessy Herrera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-05-02','C','Eduardo Jose Godoy',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-07-18','C','Eldy Leonela Ruiz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2000-07-17','P','Elvia Julia Guillen',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2008-06-05','P','Ericka Benitez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-02-01','C','Erik Gadiel Erazo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-11-02','P','Erika Rosibel Hernadez Paz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-04-01','P','Esmelin Paola Martinez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-07-01','C','Estefany Martinez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1987-06-01','P','Eva Galeas',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-03-09','C','Ever Oliva Vasquez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2008-03-03','P','Evin Margoth Sanchez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1991-07-01','P','Faustino Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2003-05-15','P','Francisco Jeronimo Molina',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1990-05-02','P','Fulgencia Reyes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-01-11','C','Gloria del Carmen Sanchez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1999-03-01','P','Gloria Maribel Munguia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2013-01-06','C','Gloria Yaneth Santos',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1992-10-01','P','Guadalupe Aracely Murillo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1998-07-16','P','Haydee Itsmary Villatoro G',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-01','C','Heber Alexander Galvez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-04-01','P','Hector Orlando Pinot Romero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-01-01','C','Helen Francisca Santos',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-06-01','C','Heydi Caballero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2008-04-01','P','Hilda Izcano',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-05-17','C','Hindira Ochoa',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1982-03-01','P','Idalia Azucena Avila Cardona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-05-02','P','Ingrid Andrea Isaula',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-01-03','P','Iris Licona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-06-01','C','Iris Nohemi Martinez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-09-02','P','Iris Robertina Barahona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1981-07-01','P','Iris Rosinda Meza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-01-01','P','Isli Gricelda Avila',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-08-01','C','Jenny Lobo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1995-08-16','P','Jorge Alberto Romero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2009-09-10','P','Jose Glen Cruz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-11-01','C','Josue Ernesto Munguia Cabrera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-11-05','C','Juana Figueroa',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1991-05-02','P','Julia Azucena Galeas',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1991-05-01','P','Julia Concepcion Navarro',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-02-15','P','Julia Marcia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-02-01','C','Karen Celena Caceres',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-01-01','C','Karen Gissela Moradel',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-08-28','C','Karen Isidro',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2001-08-06','P','Karen Yohana Urtecho',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-03-02','C','Karina Lizeth Ulloa',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-10','C','Karla Calix',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-07-03','C','Karla Josefa Romero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-08-12','C','Karla Lizeth Cardona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-09-16','P','Kathia Yohana Lemus',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-01-02','P','Katy Karina Rosales',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-01-02','P','kelin Yamileth Meza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2013-06-02','C','Kenia Mercedes Murillo Caceres',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2009-09-26','P','Keyra Zelaya',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-08-01','C','Ledis Suyapa Ruiz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-01-01','P','Leonor Martinez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-06-02','C','Lesbia Ledesma Rivera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-10-01','P','Lesbia Yamileth Zavala',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-08-01','C','Lesli Yamileth Carcamo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1990-05-02','P','Leticia Elizabeth Alonzo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1990-05-02','P','Leticia Lizeth Lanza Meza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-01','P','Leysi Patricia Espinal',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1995-09-01','P','Lida Leticia Martinez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-08-01','C','Lidia Funez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-16','C','Lili yaneth hernandez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-01','P','Lilian Edith Escobar',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1998-08-03','P','Lourdes Caceres',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-04-01','C','Lourdes Rosales',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1999-06-15','P','Lourdes Suyapa Diaz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1990-05-02','P','Lusmila Cardenas',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-06-01','C','Luz Antonia Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-05-01','C','Luz Marina Mendoza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-01-02','P','Ma. De Jesús Mencia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-10-26','P','Maira Roxana Suarez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-02','C','Marcelina Escobar',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2002-09-30','P','Mare Evelin Sovalbarro',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-01-04','C','Margarita torres',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-04-01','C','Maria Basilia Sevilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-03-08','P','Maria Cecilia Mejia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-11-01','P','Maria Del Carmen Fuentes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-01-04','C','Maria Dolores Bermudes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-05-23','C','Maria Jose Moncada',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-02-01','C','Maria Jose Munguia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-08-13','C','Maria Luz Flores',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-04-05','C','Maria Oliva Aguilera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1990-05-02','P','Maria Petrona Flores',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1998-09-01','P','Maria Victoria Pavon',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-01-01','C','Marilina Paz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-07-01','P','Marta Funez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2013-05-02','C','Martha Hernandez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-07-01','P','Martha Ramona Funez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-10-01','C','Maryuri Galvez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2008-02-01','P','Mayra Yaneth Rubi',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-07-02','C','Melsy Aguiriano',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-04-13','C','Merary Peralta',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-12-01','C','Merbelin Carrazco',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2008-03-03','P','Merlin Carolina Gutierrez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-02-01','C','Michell Rojas',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-01-01','C','Mildred Eveline Irias',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-03-25','C','Mirian Esperanza Zelaya',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-03-25','C','Mirian Esperanza Zelaya',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-07-01','P','Mirian Patricia Acosta',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2003-07-01','P','Mirian Raquel Cruz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-01','C','Nancy Carolina Turcios',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2009-10-01','P','Narcisa Sanchez Nieto',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-01','C','Nelvan Marina Mendez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-07-01','C','Ninrod Ildefonso',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-01-12','P','Nivida Guadalupe Ruiz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-04-11','C','Nohelia Consuelo Palacios',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2008-03-03','P','Nolvin Yanileth Mendez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1990-05-02','P','Norma Julieta Sandoval',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2004-04-12','P','Nusly Eduviges Henriquez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2013-03-01','P','Nuvia Silvana Guillen',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2000-05-01','P','Odalis Julissa Lozano',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1978-10-01','P','Olga doris jimenez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-01-04','C','Oscar Danilo Carrasco',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-01-04','C','Oscar Danilo Carrasco',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-01','C','Osiris Fabiola Turcios',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2007-08-17','C','Patricia Moradel',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-02-01','C','Rafael Humberto Olivera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1995-04-20','P','Raquel Consuelo Sarmiento',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-05-15','C','Rebeca Lizeth Mena',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-03-26','C','Reina Cirila Caballero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-05-16','P','Reina Margarita Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1991-05-02','P','Reina Orellana',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-05-02','P','Reinaldo Caceres',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1991-05-02','P','Reyna Maritza Baca',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-04-29','P','Rosa Dominga Sierra',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-01-01','P','Rosa Elena Herrera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2009-07-07','P','Rosa Faviana Aleman',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-08-01','C','Rosa Idalia Matute',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-08-01','P','Rosa Lidia Antunez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-05-01','C','Rosa Lidia Rosales',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-06-05','C','Rosa Lidia Ruiz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-10-01','C','Rosa Maria Garrido',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-07-01','C','Sandra Avila',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-10-01','P','Sandra Leticia Cambar',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2009-10-01','P','Sandra Lizeth Izcano',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-09-03','P','Sandra Martinez Meza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-01-02','P','Santa Isabel Aceituno',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2007-08-01','P','Sara  Elizabeth Grijalba',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-07-01','P','Sara Carolina Isaula',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-07-29','C','Seily Medina',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1999-06-16','P','Senia Corroto',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-02-08','C','Sergio Nahun Romero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-07-02','C','Seyli Maribel Medina',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-01-01','C','Sheila Maribel Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-04-13','C','Silvia Carola Pastor',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-04-12','C','Silvia Martinez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-03-26','C','Sinde Sosa',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-06-01','C','Sindi Leticia Velasquez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2013-03-01','C','Sindy Sarahi Rosales',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2002-08-19','P','Sofia Aleman',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1991-05-02','P','Soledad Oseguera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-10-01','C','Sonia Mendoza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-07-01','C','Suani Maricela Marroquin',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-01-11','C','Suany Vanessa Peralta',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2009-10-01','P','Suyapa Adalila Pacheco',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-05-05','C','Suyapa Del Carmen Castillo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2013-01-06','C','Tatiana Torres',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-02','P','Vania Alejandra Garcia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-01-27','P','Vilma Elizabeth Reyes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-08-01','C','Wendy Elizabeth Garcia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-06-01','C','Wendy Lizeth Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-10-01','C','Wendy Mariela Galvez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-07-28','C','Wendy Xiomara Santos',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-02-10','C','Wilder Eduardo Rivera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-01-01','C','Wilian Castillo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-01-01','P','Yanaris Suyapa Maldonado',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-10-01','P','Yany Martinez Sibrian',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-01-01','C','Yenci Dayana Mendoza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-11-17','P','Yeni Damary Murillo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2000-05-15','P','Yessenia del Carmen Ayala',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-07-05','C','Yilian Yaneth Avila',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-03-21','C','Yohana  lizeth pavon',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-12-02','C','Yojhana Maide Galeas',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-04-01','C','Yurian Garcia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-07','C','Zoila Alejandrina',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-03-01','P','Zulma Escoto',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-03-01','P','Zulma Yaneth Escoto',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1992-01-02','P','Juana Rosa Delgado',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-12-09','C','Elba Alejandra vindel',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-08-01','C','Alba Najera',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-09-05','C','Alma Leticia Sandoval',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-11-01','C','Alma mendez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-04-17','C','Alma Patricia Antunez Diaz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1991-05-02','P','Ana Daysi Acosta',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-04-08','C','Ana Elvira Hernandez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-05-15','C','Ana Sarmiento',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-02','C','Angel Antonio Figueroa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-10-18','P','Angel Francisco Meza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2009-09-28','P','Angela Mirella Escobar',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-09-01','C','Aracely Elvir',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-03-25','C','Arlin Maricela Reyes',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2007-02-15','P','Baleska Padilla',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-04-01','C','Bayardo Israel Sarmiento',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-01-13','C','Bessy Yolany Oliva Turcios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-01-24','C','Besy Yesenia Padilla',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-12-19','C','Bradly Josue Aguilera',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-05-01','C','Britani Fernanda Martinez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-10-03','C','Caren Leticia Carcamo',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2009-09-08','P','Carla Patricia Solorzano',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1984-10-15','P','Carlos David Ramirez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-01-29','P','Carlos Eduardo Acosta',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2013-04-22','P','Carlos Francisco Cruz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-07-01','C','Carlos Jose Murillo',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-08-22','C','Carmen Liseth Calix',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-04-11','C','Celvin Leonel rosales',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-01','C','Cesar Hernan Barahona',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-08-18','C','Cesar Hernan Jimenez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-11-15','C','Cindy Tatiana Alvarez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-05-01','C','Cinthia Marisela Rivera',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-07-01','C','Cinthia Yasmin Ruiz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-05-01','C','Claudia Maribel Turcios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-02-16','C','Cordelia Zepeda',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1999-02-04','P','Daniel Arturo Garcia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-09-01','C','Daniel Eduardo Lopez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2007-07-10','C','Daniel Ernesto Acosta',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-08-01','C','Daniel pacheco',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-02-10','C','Daysi Matute',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-07-01','C','Deiby Leonardo Zelaya',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-01-01','C','Delmy Dinora Torres',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2003-09-30','P','Denia M . Pacheco',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2007-09-14','P','Diana Meza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2000-09-18','C','Dilcia Aracely Sanchez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-04-09','C','Dolores Argentina Mendoza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1987-10-01','P','Doris A. Mejia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-07-01','C','Doris Antunez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-07-01','C','Dulce Gabriela Rosales',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1990-09-03','P','Duma Rivera Hernández',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1999-03-15','P','Edson Figueroa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-07-01','C','Erick Fabricio Alvarez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-03-20','C','Erick Mendoza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-04-12','C','Erika Lopez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-07-25','C','Eva Leonor Calix',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-03','C','Felicita Discua',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2004-11-11','P','Felix Galel Zelaya',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-01-06','C','Fernanda Cardona',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-01-01','C','Flavio Rene Sarmiento',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-12-05','C','Franci Yolani Torres',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-09-14','P','Franklin Gerando Reyes',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-06-01','C','Fredy Rutilio Juarez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-01','P','Gabriela Savala',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1984-08-15','P','Georgina Padilla Munguia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-04-01','C','Gicela Yolanda Chavez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-01-03','P','Glendy Yohana Varela',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-08-01','C','Gloria Maritza Barahona',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-02-01','C','Gustavo Adolfo Villatoro',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-06-13','C','Harvin Ariel Cruz Lagos',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-04-01','C','Hebe Gardenia R. Flores',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-02-02','C','Hector Junior Medina',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-05-01','P','Heidi Ninoska Padilla',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-09-16','C','Iliana Clareth Rivera',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-11-01','P','Ilsy Geanina Godoy Varela',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-07-01','C','Ina Edelda Pacheco',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-12-01','C','Iris Esmeralda Sauceda',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2007-04-13','P','Iris Yolanda Meza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-04-01','C','Iris Yolani Cruz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-07-01','C','Ivan Adalid Najera',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-09-12','C','Jely Senaida Pacheco',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-16','C','Jessica Xiomara H. Ramos',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-05-06','C','Jose Armando Adelino',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-04-25','C','Jose Francisco Romero',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2001-09-17','P','Jose Gales',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-07-01','C','Jose Luis Coleman',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1980-11-10','P','José Romero Martinez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-04-01','C','Joselin Martinez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-02','P','Josue Moises Romero',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-04-02','C','Juan Francisco Miralda',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1999-01-11','P','Juan Pablo Elvir',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-09-03','P','Karen Emilia Zuniga',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-01','C','Karen Mendez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-07-06','P','Karla Gissela Cruz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-07-03','C','Karla Josefa Romero',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-10-01','C','Karla Villatoro',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-02-16','C','Kefy Yorleni Alvarado',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-08-12','C','Keila Turcios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-03-01','P','Kenia Lizeth Gomez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2009-09-10','P','Keyla Matute',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-11-01','P','Kleymer Stephenie lopez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-11-17','C','Kyrian Vanely Galeas',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-04-01','C','Laritza Gissela Muñoz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-01','P','Lesly Carolina Calix',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-04-01','C','Lesly Maribel Carcamo',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1996-09-03','P','Leticia Antunez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-06-03','C','Leticia Consuelo Mena',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-01-02','P','Leticia Velásquez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1996-09-01','P','Lexsa Inestroza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-01-01','C','Lidia Isabel Sanchez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1990-09-03','P','Lilian Patricia Coleman',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-08-10','C','Luis Fernando Sarmiento',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-08-02','C','Luisa Sarmiento',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-04-01','C','Luz Marina Rodriguez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-07-15','C','Marcia Dolores Acosta',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-01-01','C','Maria Caridad Figueroa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-11-01','P','Maria Del Carmen Martinez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1981-04-15','P','Maria Dolores Mairena',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-09-01','C','Maria Elena Guifarro',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-07-01','C','Maria Jose Murillo',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-05-20','C','Maria Teodula Galindo',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-04-08','C','Maria Zuniga',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-01-02','P','Maribel Antunez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2013-04-22','P','Maricela Turcios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-15','C','Marin Xiomara Turcios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-06-15','C','Mario Steve Barrios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-01-01','P','Martha Jissela Castro',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-02-01','C','Martha Josefa Antunez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-05-01','C','Maylin Fuentes',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-07','C','Mery Corina Galvez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1987-04-01','P','Miguel Antonio Flores',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-08-01','C','Milton Joel Torrez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2006-06-23','P','Milton Mateo Montalvan',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-04-07','C','Mirian Yamileth Baca',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-05-01','C','Mirian Yolanda Figueroa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1996-08-16','P','Mirna Elisa Figueroa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-04-01','C','Nasly Samira Amador',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-07-01','C','Nelly Orfelina Figueroa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-02-01','C','Nery Alexis Castellanos',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-18','C','Nilda Lizeth Ochoa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-01-01','C','Nilda Sadith Palacios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-11','C','Nimia Azucena Bargas M.',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-01-08','C','Nora Reynelda Suarez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-02-01','C','Norma Dixiana Torrez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-03-31','C','Norman David Guifarro',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-05-13','P','Normandina del C. Flores',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1991-06-03','P','Nusly del Carmen Aguilar',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-01-04','P','Olga maria Vindel',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-07-01','C','Ondina del carmen Pavon',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-04-05','C','Oscar Armando Matute',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-01-09','C','Osiris melissa Torres',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-08-01','P','Osman Nolberto Castellano',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1999-09-01','P','Owilson Oqueli Amador',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-04-26','C','Pablo Ernesto Munguia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2000-05-18','P','Patricia Elizabeth Romero',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-10-27','P','Patricia guadalupe Rosales',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-02-03','C','Paul Izcoa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-08-01','C','Pedro Rafael Lanza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-01-01','C','Ramon Alfredo Lanza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-01-01','C','Ramon Hostilio Aguilar',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-15','C','Rene Alexander Zelaya',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-03-13','C','Richart Humberto Irias',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1990-05-02','P','Rina Lizette Madrid',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1994-04-01','P','Rony Javier Rodriguez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-11-01','C','Rosa Mariela Diaz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2008-03-28','P','Rosa Yesenia Garcia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-05-06','C','Rosemary Suarez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2017-03-01','C','Rosmery piedad Garcia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-11-01','P','Rossel Wilfredo Murillo',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-06-30','C','Sandra Araceli Meza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2013-02-08','P','Sandra Carolina Vazquez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-07-01','C','Sandra Marisol Bonilla',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2015-08-24','C','Sandra Patricia Billalovos',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1987-04-01','P','Santos Dioselina Paz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2011-06-06','P','Sara Beatris Castro',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-10','C','Sara Lastenia Godoy',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1997-10-01','P','Seily Esmeralda Echeverria',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2007-09-17','P','Sergio B. Muños',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2012-01-17','C','Seyda Meza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2018-03-12','C','Seydy Areli Andino',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-08','C','Silvia Angelina Ruiz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2005-11-01','P','Sonia del carmen escobar',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2014-06-07','C','Sonia Iraena Amador',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-07-01','C','Suyapa Escobar',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-05-02','P','Tania Elizabeth Caceres',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2006-03-13','P','Vilma Dolores Zelaya',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2003-02-17','P','Walter Abel Martinez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-09-01','C','Wendy Giron',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-03-02','C','Wendy Gricelda Rosales',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-04-12','C','Wendy Sthefany crozier',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2003-08-18','P','Xenia Funez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2000-04-01','P','Yadira Balesca Mejia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-04-24','C','Yaneth Hernandez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2013-04-22','P','Yasaira Meliza Martinez T.',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-08-16','C','Yasmina Acosta',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2010-06-08','C','Yesica Patricia Antunez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2003-04-03','C','Yessika Munguia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2019-04-03','C','Yolani Gonzales',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2016-05-19','C','Yulian Yamilec Padilla',3,'NO');
