SET IDENTITY_INSERT TipoEmpleado ON

INSERT [dbo].[TipoEmpleado] ([IDTipo], [Descripcion]) VALUES (1, N'Medico')
INSERT [dbo].[TipoEmpleado] ([IDTipo], [Descripcion]) VALUES (2, N'Enfermeria')
INSERT [dbo].[TipoEmpleado] ([IDTipo], [Descripcion]) VALUES (3, N'General')

INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('4/6/2007','P','Abel De Jesus Cerrato',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2010','P','Alberto David Bonilla',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2019','C','Amy Lagos',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/2015','C','Amy Lizeth Hernandez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/8/1998','P','Ana Gloria Ramos',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/3/2010','C','Ana Ofelia Motiño',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/2019','C','Axel Javier Zelaya',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2019','P','Brenda Concepcion Cruz',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('13/6/2005','P','Carlos Ariel Tróchez Zelaya',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2016','C','Celeo Joel Diaz',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2019','P','Cesar Alberto Martinez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2010','C','Cindy Lyonela Garcia M.',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/1/2016','C','Cinthia Carolina Padilla',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/1996','P','Claudia Marina Sarmiento',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/1996','P','Clinton Olivera',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2006','P','Daisy Yorleni Rodriguez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/1992','P','Daniel Antonio Ochoa',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2019','C','Daniel Rivera',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('4/3/2008','C','David Gerardo Bracamonte',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2017','C','Digna Melissa Galvez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2011','C','Edgardo Omar Segura',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2016','C','Edwin Arturo Fernandez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('6/3/2018','C','Ela Maria Zelaya',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/1986','P','Ely Catalina Dominguez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('13/6/2005','P','Eneida Jimenez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2018','C','Erick Fernando Aguiriano',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('25/7/2017','C','Eva Leonor Calix',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('6/8/2012','P','Frida Nadesda Mejia',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2013','C','Gloria Maria Inestroza',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('20/10/2000','P','Hector Escoto',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2005','P','Hector Saul Lopez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2008','P','Hector Tulio Garcia',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/2017','C','Hilda Xiomara Castellano',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2019','C','Ilsi Donaire',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2005','P','Iris Raquel Benitez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2016','C','Ivonne Waleska Canales',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/11/1997','P','Javier Enrique Zelaya',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2019','P','Joel Turcios',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2006','P','Jose Antonio Zelaya',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2011','P','Jose Braz Guimaraez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/8/1998','P','Jose Enrique Mendez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('4/6/2007','P','Jose Leon Rivera',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2010','P','Jose Luis Pinto',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/1999','P','Juana Lizeth Cruz',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/2017','C','Julissa Yaneth Andrade',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2006','P','Lesbia Yabeth Sandoval',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('4/6/2007','P','Ligia Geraldina Umaña',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2016','C','Lucy Maribel Martinez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('24/10/2014','C','Luis Carlos Trochez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2019','P','Luis Carlos Trochez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2017','C','Luis Fernando Aguilar',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2008','P','Luis Guillermo Moraga',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('12/2/2007','P','Luis Ramon Valderramos',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2019','P','Lyn Dayana Olivera',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2006','C','Marcos Rolando Medina',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2010','P','Mario Jose Gonzales',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2005','P','Melba Patricia Cruz',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2015','C','Melissa Lilibeth Turcios',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/8/1998','P','Mericia Yolibeth Breve',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('10/4/2010','C','Napoleon Valerio Zapata',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/1993','C','Nicolas Alberto Irias',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2018','C','Oly Lideny Oliva',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2014','C','Orquidea Zelaya',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2019','P','Osman Noel Garcia Avila',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2019','C','Rafael Eduardo Santos',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2010','P','Ramon Edgardo Irias',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2004','P','Ramon Henriquez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2016','C','Sadia Melissa Banegas',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('13/6/2005','P','Samuel Gustavo Rodriguez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2010','P','Sandra Carlota Matute',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2019','P','Santos Jubinaldo Flores',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2010','P','Sara Carolina Paz',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/2019','C','Sergio Alejandro Cerna',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/11/1997','P','Silvia Yaneth Hernandez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2018','C','Teresa Maria Reyes',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2016','C','Vanessa Jose Diaz',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/11/1997','P','Victor Manuel Zepeda',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('16/2/2018','C','Vilma Galvez',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2018','C','Wilian Alexander Duron',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2005','P','Wilson Sabonge',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/1996','P','Ziomara Yamileth Ceballos',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/1993','P','Zoila Adilia Rivera',1,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/3/2008','P','Adonia Anaizel Diaz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2019','C','Alba Elizabeth Flores',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2014','C','Alba Leticia Tejeda Cano',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2015','P','Alba Lopez Montalvan',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/1980','P','Alba Margarita Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/11/2016','P','Alba Maria Reyes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('11/6/2010','C','Alba Maricela Figueroa',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/11/2016','P','Alba Marina Pavon',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/1989','P','Alba Marina Vásquez D',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/2012','C','Alba Yadira Rodriguez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('20/2/2017','C','Alex Matute',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/2015','C','Altagracia del carmen reyes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/1978','P','Amalia Carmén Osorio Garrido',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2012','C','Amanda Lucila Calix',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2019','C','Ana Cerna',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/1999','P','Ana lizeth Ayala',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2019','C','Ana Maria Cartejena',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2012','C','Ana Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('12/4/1999','P','Ana Rosa Romero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/1985','P','Ana Rosario Hdz Montes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2012','C','Ana Victoria Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/11/1997','P','Anabel del Carmen Cardona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/1997','P','Angela Maritza Funez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/6/1991','P','Angela Padilla Meza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/2011','C','Angelica Yamileth Bardales',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('19/11/2019','C','Ansy Marilu Puerto',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/7/2004','P','Aracely Maribel Gomez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/2/1985','P','Berlinda Lily Rodriguez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/1993','P','Bertha Estela Turcios',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/2014','C','Bessy Mejia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/2017','C','Bessy Yasmin Flores',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/2016','C','Betina Petronila Turcios',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/2016','C','Betina Petronila turcios',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1990','P','Bety Leticia Varela',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/1987','P','Blanca Lidia Sierra',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/2010','P','Breiner Paul Muñoz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2015','P','Brenda Flores',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('23/9/2005','P','Carlos Everto Duarte',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('4/1/2010','P','Carlos ruben varela',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('4/4/1991','P','Carmen Rosmeri Alonzo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2015','C','Cindi Bonilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/2018','C','Cindi Graciel elvir',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/9/2018','P','Claudia Barahona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2014','P','Claudia Sarmiento',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/1/2005','P','Coritza Landelina Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2008','C','Damari Valladares',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('4/1/2019','C','Damaris Mireya Galvez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('22/8/2014','P','Dariela Elena Medina',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2001','P','Dayanara Varinia Licona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/7/1990','P','Daysi Sagrario Hernandez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('20/6/2016','C','Deisy Pineda',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2012','P','Denis Alaberto Andino',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2016','P','Deysi Alejandrina Mendoza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/2/2018','C','Deysi Maria Moradel',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/2/2018','C','Deysi Moradel Carias',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('5/4/2013','C','Diana solorzano',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2014','C','Diana Yamileth Lopez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1990','P','Digna Maribel Garcia Suarez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('19/4/1999','P','Dilian Margoth Acosta',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/2016','C','Dina Veronica Carias',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('26/2/2007','P','Dina Yolani Acosta',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2011','P','Doris Antonia Licona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('20/9/2006','P','Dulce Paz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/2/2005','P','Dulmi Yolani Romero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('26/3/2015','C','Eda Beatris Hernandez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('5/5/2014','C','Edis Etelvina Rodas',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2015','P','Edith Jessy Herrera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/2017','C','Eduardo Jose Godoy',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('18/7/2019','C','Eldy Leonela Ruiz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('17/7/2000','P','Elvia Julia Guillen',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('5/6/2008','P','Ericka Benitez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/2017','C','Erik Gadiel Erazo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/11/2015','P','Erika Rosibel Hernadez Paz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2016','P','Esmelin Paola Martinez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2019','C','Estefany Martinez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/1987','P','Eva Galeas',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('9/3/2011','C','Ever Oliva Vasquez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/3/2008','P','Evin Margoth Sanchez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/1991','P','Faustino Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/5/2003','P','Francisco Jeronimo Molina',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1990','P','Fulgencia Reyes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('11/1/2017','C','Gloria del Carmen Sanchez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/1999','P','Gloria Maribel Munguia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('6/1/2013','C','Gloria Yaneth Santos',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/1992','P','Guadalupe Aracely Murillo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('16/7/1998','P','Haydee Itsmary Villatoro G',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2014','C','Heber Alexander Galvez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2016','P','Hector Orlando Pinot Romero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2015','C','Helen Francisca Santos',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2016','C','Heydi Caballero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2008','P','Hilda Izcano',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('17/5/2019','C','Hindira Ochoa',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/1982','P','Idalia Azucena Avila Cardona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/2016','P','Ingrid Andrea Isaula',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/1/2005','P','Iris Licona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2014','C','Iris Nohemi Martinez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/9/2015','P','Iris Robertina Barahona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/1981','P','Iris Rosinda Meza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2011','P','Isli Gricelda Avila',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2015','C','Jenny Lobo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('16/8/1995','P','Jorge Alberto Romero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('10/9/2009','P','Jose Glen Cruz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/11/2011','C','Josue Ernesto Munguia Cabrera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('5/11/2018','C','Juana Figueroa',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1991','P','Julia Azucena Galeas',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/1991','P','Julia Concepcion Navarro',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/2/2005','P','Julia Marcia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/2016','C','Karen Celena Caceres',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2016','C','Karen Gissela Moradel',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('28/8/2014','C','Karen Isidro',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('6/8/2001','P','Karen Yohana Urtecho',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/3/2012','C','Karina Lizeth Ulloa',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('10/7/2014','C','Karla Calix',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/7/2012','C','Karla Josefa Romero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('12/8/2010','C','Karla Lizeth Cardona',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('16/9/1997','P','Kathia Yohana Lemus',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2015','P','Katy Karina Rosales',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2015','P','kelin Yamileth Meza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/6/2013','C','Kenia Mercedes Murillo Caceres',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('26/9/2009','P','Keyra Zelaya',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2017','C','Ledis Suyapa Ruiz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2011','P','Leonor Martinez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/6/2011','C','Lesbia Ledesma Rivera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/1997','P','Lesbia Yamileth Zavala',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2015','C','Lesli Yamileth Carcamo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1990','P','Leticia Elizabeth Alonzo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1990','P','Leticia Lizeth Lanza Meza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2014','P','Leysi Patricia Espinal',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/1995','P','Lida Leticia Martinez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2017','C','Lidia Funez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('16/6/2010','C','Lili yaneth hernandez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2014','P','Lilian Edith Escobar',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/8/1998','P','Lourdes Caceres',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2017','C','Lourdes Rosales',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/6/1999','P','Lourdes Suyapa Diaz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1990','P','Lusmila Cardenas',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2016','C','Luz Antonia Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/2016','C','Luz Marina Mendoza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/1997','P','Ma. De Jesús Mencia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('26/10/2005','P','Maira Roxana Suarez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2019','C','Marcelina Escobar',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('30/9/2002','P','Mare Evelin Sovalbarro',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('4/1/2016','C','Margarita torres',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2015','C','Maria Basilia Sevilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('8/3/2005','P','Maria Cecilia Mejia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/11/2016','P','Maria Del Carmen Fuentes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('4/1/2016','C','Maria Dolores Bermudes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('23/5/2014','C','Maria Jose Moncada',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/2016','C','Maria Jose Munguia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('13/8/2016','C','Maria Luz Flores',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('5/4/2016','C','Maria Oliva Aguilera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1990','P','Maria Petrona Flores',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/1998','P','Maria Victoria Pavon',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2016','C','Marilina Paz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2015','P','Marta Funez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/2013','C','Martha Hernandez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2015','P','Martha Ramona Funez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/2019','C','Maryuri Galvez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/2008','P','Mayra Yaneth Rubi',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/7/2016','C','Melsy Aguiriano',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('13/4/2015','C','Merary Peralta',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/12/2018','C','Merbelin Carrazco',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/3/2008','P','Merlin Carolina Gutierrez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/2017','C','Michell Rojas',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2017','C','Mildred Eveline Irias',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('25/3/2019','C','Mirian Esperanza Zelaya',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('25/3/2019','C','Mirian Esperanza Zelaya',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2016','P','Mirian Patricia Acosta',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2003','P','Mirian Raquel Cruz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2014','C','Nancy Carolina Turcios',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/2009','P','Narcisa Sanchez Nieto',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2019','C','Nelvan Marina Mendez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2019','C','Ninrod Ildefonso',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('12/1/1997','P','Nivida Guadalupe Ruiz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('11/4/2016','C','Nohelia Consuelo Palacios',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/3/2008','P','Nolvin Yanileth Mendez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1990','P','Norma Julieta Sandoval',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('12/4/2004','P','Nusly Eduviges Henriquez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2013','P','Nuvia Silvana Guillen',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/2000','P','Odalis Julissa Lozano',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/1978','P','Olga doris jimenez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('4/1/2016','C','Oscar Danilo Carrasco',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('4/1/2016','C','Oscar Danilo Carrasco',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2014','C','Osiris Fabiola Turcios',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('17/8/2007','C','Patricia Moradel',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/2016','C','Rafael Humberto Olivera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('20/4/1995','P','Raquel Consuelo Sarmiento',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/5/2019','C','Rebeca Lizeth Mena',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('26/3/2015','C','Reina Cirila Caballero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('16/5/2016','P','Reina Margarita Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1991','P','Reina Orellana',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/2016','P','Reinaldo Caceres',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1991','P','Reyna Maritza Baca',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('29/4/1997','P','Rosa Dominga Sierra',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2011','P','Rosa Elena Herrera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('7/7/2009','P','Rosa Faviana Aleman',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2011','C','Rosa Idalia Matute',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2005','P','Rosa Lidia Antunez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/2016','C','Rosa Lidia Rosales',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('5/6/2018','C','Rosa Lidia Ruiz',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/2017','C','Rosa Maria Garrido',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2018','C','Sandra Avila',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/1997','P','Sandra Leticia Cambar',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/2009','P','Sandra Lizeth Izcano',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/9/2018','P','Sandra Martinez Meza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2015','P','Santa Isabel Aceituno',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2007','P','Sara  Elizabeth Grijalba',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2016','P','Sara Carolina Isaula',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('29/7/2017','C','Seily Medina',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('16/6/1999','P','Senia Corroto',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('8/2/2016','C','Sergio Nahun Romero',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/7/2017','C','Seyli Maribel Medina',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2018','C','Sheila Maribel Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('13/4/2012','C','Silvia Carola Pastor',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('12/4/2016','C','Silvia Martinez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('26/3/2015','C','Sinde Sosa',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2016','C','Sindi Leticia Velasquez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2013','C','Sindy Sarahi Rosales',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('19/8/2002','P','Sofia Aleman',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1991','P','Soledad Oseguera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/2011','C','Sonia Mendoza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2017','C','Suani Maricela Marroquin',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('11/1/2011','C','Suany Vanessa Peralta',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/2009','P','Suyapa Adalila Pacheco',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('5/5/2015','C','Suyapa Del Carmen Castillo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('6/1/2013','C','Tatiana Torres',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2019','P','Vania Alejandra Garcia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('27/1/2010','P','Vilma Elizabeth Reyes',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2018','C','Wendy Elizabeth Garcia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2016','C','Wendy Lizeth Padilla',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/2017','C','Wendy Mariela Galvez',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('28/7/2015','C','Wendy Xiomara Santos',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('10/2/2017','C','Wilder Eduardo Rivera',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2017','C','Wilian Castillo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2011','P','Yanaris Suyapa Maldonado',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/1997','P','Yany Martinez Sibrian',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2016','C','Yenci Dayana Mendoza',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('17/11/1997','P','Yeni Damary Murillo',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/5/2000','P','Yessenia del Carmen Ayala',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('5/7/2012','C','Yilian Yaneth Avila',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('21/3/2019','C','Yohana  lizeth pavon',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/12/2016','C','Yojhana Maide Galeas',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2019','C','Yurian Garcia',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('7/1/2019','C','Zoila Alejandrina',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2005','P','Zulma Escoto',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2005','P','Zulma Yaneth Escoto',2,'SI');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/1992','P','Juana Rosa Delgado',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('9/12/2019','C','Elba Alejandra vindel',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2014','C','Alba Najera',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('5/9/2011','C','Alma Leticia Sandoval',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/11/2012','C','Alma mendez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('17/4/2012','C','Alma Patricia Antunez Diaz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1991','P','Ana Daysi Acosta',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('8/4/2010','C','Ana Elvira Hernandez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/5/2014','C','Ana Sarmiento',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/7/2014','C','Angel Antonio Figueroa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('18/10/2005','P','Angel Francisco Meza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('28/9/2009','P','Angela Mirella Escobar',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/2019','C','Aracely Elvir',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('25/3/2017','C','Arlin Maricela Reyes',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/2/2007','P','Baleska Padilla',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2014','C','Bayardo Israel Sarmiento',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('13/1/2016','C','Bessy Yolany Oliva Turcios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('24/1/2012','C','Besy Yesenia Padilla',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('19/12/2018','C','Bradly Josue Aguilera',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/2016','C','Britani Fernanda Martinez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/10/2019','C','Caren Leticia Carcamo',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('8/9/2009','P','Carla Patricia Solorzano',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/10/1984','P','Carlos David Ramirez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('29/1/2015','P','Carlos Eduardo Acosta',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('22/4/2013','P','Carlos Francisco Cruz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2019','C','Carlos Jose Murillo',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('22/8/2010','C','Carmen Liseth Calix',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('11/4/2016','C','Celvin Leonel rosales',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2014','C','Cesar Hernan Barahona',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('18/8/2014','C','Cesar Hernan Jimenez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/11/2017','C','Cindy Tatiana Alvarez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/2015','C','Cinthia Marisela Rivera',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2016','C','Cinthia Yasmin Ruiz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/2015','C','Claudia Maribel Turcios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('16/2/2018','C','Cordelia Zepeda',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('4/2/1999','P','Daniel Arturo Garcia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/2017','C','Daniel Eduardo Lopez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('10/7/2007','C','Daniel Ernesto Acosta',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2014','C','Daniel pacheco',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('10/2/2011','C','Daysi Matute',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2016','C','Deiby Leonardo Zelaya',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2018','C','Delmy Dinora Torres',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('30/9/2003','P','Denia M . Pacheco',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('14/9/2007','P','Diana Meza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('18/9/2000','C','Dilcia Aracely Sanchez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('9/4/2010','C','Dolores Argentina Mendoza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/1987','P','Doris A. Mejia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2010','C','Doris Antunez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2016','C','Dulce Gabriela Rosales',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/9/1990','P','Duma Rivera Hernández',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/3/1999','P','Edson Figueroa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2017','C','Erick Fabricio Alvarez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('20/3/2017','C','Erick Mendoza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('12/4/2010','C','Erika Lopez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('25/7/2017','C','Eva Leonor Calix',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/6/2010','C','Felicita Discua',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('11/11/2004','P','Felix Galel Zelaya',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('6/1/2016','C','Fernanda Cardona',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('0/1/1900','P','Flanklin Jimenez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2017','C','Flavio Rene Sarmiento',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('5/12/2016','C','Franci Yolani Torres',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('14/9/2011','P','Franklin Gerando Reyes',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/6/2015','C','Fredy Rutilio Juarez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2014','P','Gabriela Savala',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/8/1984','P','Georgina Padilla Munguia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2016','C','Gicela Yolanda Chavez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/1/2005','P','Glendy Yohana Varela',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2017','C','Gloria Maritza Barahona',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/2017','C','Gustavo Adolfo Villatoro',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('13/6/2016','C','Harvin Ariel Cruz Lagos',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2014','C','Hebe Gardenia R. Flores',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/2/2017','C','Hector Junior Medina',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/2011','P','Heidi Ninoska Padilla',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('16/9/2019','C','Iliana Clareth Rivera',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/11/2018','P','Ilsy Geanina Godoy Varela',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2010','C','Ina Edelda Pacheco',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/12/2016','C','Iris Esmeralda Sauceda',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('13/4/2007','P','Iris Yolanda Meza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2018','C','Iris Yolani Cruz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2016','C','Ivan Adalid Najera',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('12/9/2012','C','Jely Senaida Pacheco',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('16/6/2010','C','Jessica Xiomara H. Ramos',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('6/5/2019','C','Jose Armando Adelino',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('25/4/2019','C','Jose Francisco Romero',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('17/9/2001','P','Jose Gales',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2017','C','Jose Luis Coleman',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('10/11/1980','P','José Romero Martinez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2015','C','Joselin Martinez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2019','P','Josue Moises Romero',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/4/2019','C','Juan Francisco Miralda',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('11/1/1999','P','Juan Pablo Elvir',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/9/2018','P','Karen Emilia Zuniga',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2014','C','Karen Mendez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('6/7/2011','P','Karla Gissela Cruz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/7/2012','C','Karla Josefa Romero',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/2010','C','Karla Villatoro',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('16/2/2017','C','Kefy Yorleni Alvarado',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('12/8/2010','C','Keila Turcios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2011','P','Kenia Lizeth Gomez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('10/9/2009','P','Keyla Matute',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/11/2018','P','Kleymer Stephenie lopez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('17/11/2017','C','Kyrian Vanely Galeas',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2019','C','Laritza Gissela Muñoz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2014','P','Lesly Carolina Calix',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2012','C','Lesly Maribel Carcamo',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/9/1996','P','Leticia Antunez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/6/2015','C','Leticia Consuelo Mena',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/1997','P','Leticia Velásquez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/1996','P','Lexsa Inestroza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2018','C','Lidia Isabel Sanchez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/9/1990','P','Lilian Patricia Coleman',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('10/8/2010','C','Luis Fernando Sarmiento',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/8/2010','C','Luisa Sarmiento',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2018','C','Luz Marina Rodriguez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/7/2019','C','Marcia Dolores Acosta',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2018','C','Maria Caridad Figueroa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/11/2016','P','Maria Del Carmen Martinez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/4/1981','P','Maria Dolores Mairena',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/2012','C','Maria Elena Guifarro',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2019','C','Maria Jose Murillo',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('20/5/2019','C','Maria Teodula Galindo',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('8/4/2010','C','Maria Zuniga',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/1/2019','P','Maribel Antunez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('22/4/2013','P','Maricela Turcios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/6/2010','C','Marin Xiomara Turcios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/6/2018','C','Mario Steve Barrios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2014','P','Martha Jissela Castro',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/2012','C','Martha Josefa Antunez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/2014','C','Maylin Fuentes',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('7/6/2010','C','Mery Corina Galvez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/1987','P','Miguel Antonio Flores',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2014','C','Milton Joel Torrez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('23/6/2006','P','Milton Mateo Montalvan',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('7/4/2010','C','Mirian Yamileth Baca',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/5/2017','C','Mirian Yolanda Figueroa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('16/8/1996','P','Mirna Elisa Figueroa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2012','C','Nasly Samira Amador',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2014','C','Nelly Orfelina Figueroa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/2017','C','Nery Alexis Castellanos',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('18/6/2010','C','Nilda Lizeth Ochoa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2012','C','Nilda Sadith Palacios',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('11/6/2010','C','Nimia Azucena Bargas M.',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('8/1/2016','C','Nora Reynelda Suarez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/2/2012','C','Norma Dixiana Torrez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('31/3/2017','C','Norman David Guifarro',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('13/5/2005','P','Normandina del C. Flores',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/6/1991','P','Nusly del Carmen Aguilar',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('4/1/2011','P','Olga maria Vindel',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2012','C','Ondina del carmen Pavon',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('5/4/2010','C','Oscar Armando Matute',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('9/1/2012','C','Osiris melissa Torres',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2015','P','Osman Nolberto Castellano',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/1999','P','Owilson Oqueli Amador',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('26/4/2010','C','Pablo Ernesto Munguia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('18/5/2000','P','Patricia Elizabeth Romero',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('27/10/2005','P','Patricia guadalupe Rosales',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/2/2017','C','Paul Izcoa',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/8/2019','C','Pedro Rafael Lanza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2016','C','Ramon Alfredo Lanza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/1/2017','C','Ramon Hostilio Aguilar',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('15/6/2010','C','Rene Alexander Zelaya',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('13/3/2017','C','Richart Humberto Irias',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/1990','P','Rina Lizette Madrid',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/1994','P','Rony Javier Rodriguez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/11/2017','C','Rosa Mariela Diaz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('28/3/2008','P','Rosa Yesenia Garcia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('6/5/2019','C','Rosemary Suarez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/3/2017','C','Rosmery piedad Garcia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/11/2018','P','Rossel Wilfredo Murillo',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('30/6/2014','C','Sandra Araceli Meza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('8/2/2013','P','Sandra Carolina Vazquez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2015','C','Sandra Marisol Bonilla',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('24/8/2015','C','Sandra Patricia Billalovos',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/1987','P','Santos Dioselina Paz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('6/6/2011','P','Sara Beatris Castro',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('10/6/2010','C','Sara Lastenia Godoy',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/10/1997','P','Seily Esmeralda Echeverria',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('17/9/2007','P','Sergio B. Muños',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('17/1/2012','C','Seyda Meza',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('12/3/2018','C','Seydy Areli Andino',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('8/6/2010','C','Silvia Angelina Ruiz',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/11/2005','P','Sonia del carmen escobar',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('7/6/2014','C','Sonia Iraena Amador',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/7/2010','C','Suyapa Escobar',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/5/2016','P','Tania Elizabeth Caceres',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('13/3/2006','P','Vilma Dolores Zelaya',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('17/2/2003','P','Walter Abel Martinez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/9/2016','C','Wendy Giron',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('2/3/2016','C','Wendy Gricelda Rosales',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('12/4/2016','C','Wendy Sthefany crozier',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('18/8/2003','P','Xenia Funez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('1/4/2000','P','Yadira Balesca Mejia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('24/4/2019','C','Yaneth Hernandez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('22/4/2013','P','Yasaira Meliza Martinez T.',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('16/8/2010','C','Yasmina Acosta',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('8/6/2010','C','Yesica Patricia Antunez',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/4/2003','C','Yessika Munguia',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('3/4/2019','C','Yolani Gonzales',3,'NO');
INSERT INTO Empleado(FechaIngreso,TipoContrato,Nombre,TipoEmpleado,TieneProfilactica) VALUES ('19/5/2016','C','Yulian Yamilec Padilla',3,'NO');